### ISSUE TITLE
Allow seconds in time setting

### ISSUE THREAD

**Issue by GalaxySH** [jaden/SnapTimer#23]
It only seems to accept minutes when setting the timer, it would meet my needs if it allowed seconds. It won't even allow me to set minutes as a decimal.

**Comment by jaden** [comment]
That's as it was designed for simplicity. If you want to use seconds instead of minutes, you can add `SecondsMode=1` to the [Main] section of your SnapTimer.ini file and it will treat the numbers you enter as seconds.

**Comment by GalaxySH** [comment]
I understand, thank you for the solution. It's fine since there is a way to configure that.
