### ISSUE TITLE
Request for new features

### ISSUE THREAD

**Issue by Truman78es** [jaden/SnapTimer#29]
It would be very interesting to have an option to have the timer in full screen, not within a window. And having that full screen mode, I have another need to be able to align the clock in the center of the screen, both horizontally and vertically, so that only the clock appears on the screen, something like this:

![Captura de pantalla (111)](https://github.com/jaden/SnapTimer/assets/63008475/88e63e71-c27b-4ba2-b49c-18947bbe2cba)

Thank you very much for the contribution and I hope you can add this new functionality.

**Comment by jaden** [comment]
I appreciate your input, but I'm not actively working on this project anymore.
