### ISSUE TITLE
Pause/Run 1 click

### ISSUE THREAD

**Issue by Silent83PL** [jaden/SnapTimer#5]
I can't pause time by clicking on timer, what is making problem?

**Comment by jaden** [comment]
I'll need some more information to be able to help. Does clicking on the pause button work?

**Comment by Silent83PL** [comment]
No, clicking on pause doesn't work also. Pause button is inactive.

**Comment by jaden** [comment]
It sounds like the window doesn't have focus. Is it possible you opened the settings dialog when this happened?

**Comment by Silent83PL** [comment]
No setting dialog isn't open. I just notice that when i click PAUSE button time skip 1 second (it countdown 2 sec instead of 1 in the moment of click). Maybe you can send me the sourcecode of Snaptime ver 0.1 which was working perfect for me?

**Comment by jaden** [comment]
The source code is all here on Github. Feel free to build it yourself with Lazarus. Strange though, this is the first I've heard of this behavior.
