### ISSUE TITLE
Feature Request: Configurable [X] button behavior

### ISSUE THREAD

**Issue by mrobb** [jaden/SnapTimer#8]
Hi Dan,

What do you think about adding a dropdown menu in the options that looks like this:

```
When clicking on [X] button:
- Terminate this program immediately
- Minimize to system tray
```

This is a feature I appreciate in other programs I use.

e.g.:
![image](https://cloud.githubusercontent.com/assets/298306/20869580/90a87bf8-ba32-11e6-9ad3-4ccf64264fde.png)

**Comment by jaden** [comment]
There's already a setting to make the minimize button go to the system tray, so the functionality is there, just two doors to the left :)

**Comment by mrobb** [comment]
@jaden Fair enough, the functionality does exist :bowtie: 

In case at some point you decide to reconsider, here's a screenshot from KeePass for inspiration:

![image](https://cloud.githubusercontent.com/assets/298306/20916371/be46a370-bb48-11e6-9963-ee24f1083d85.png)

**Comment by jaden** [comment]
Thanks for the reference point. I love KeePass and use it daily, but it seems like an odd design decision. If both boxes are checked, the minimize button is no different than the close button.

**Comment by mrobb** [comment]
Yep, I agree, we'll probably never see it recommended in any GUI "best practices" 😁 but nevertheless I think for some apps, which are generally left running, it's an ok workaround to prevent accidental closing (e.g. Skype comes to mind).
